/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import ImageWithText from '../ImageWithText/ImageWithText';

const MyComponent: React.FC = () => {
  return (
    <main className="box-border flex relative flex-col shrink-0 h-full grow-0">
      <ImageWithText
        imageSrc="https://cdn.builder.io/api/v1/image/assets%2Fba6067db386645d69360706d06cfc8a6%2F0c3a9c06f3354117986afef88d0c1b56"
        title="Enter some text..."
        description="Enter some text..."
      />
    </main>
  );
};

export default MyComponent;