/**
 * This code was generated by Builder.io.
 */
import Image from 'next/image';
import React from 'react';

interface ImageWithTextProps {
  imageSrc: string;
  title: string;
  description: string;
}

const ImageWithText: React.FC<ImageWithTextProps> = ({ imageSrc, title, description }) => {
  return (
    <article className="box-border flex relative flex-col shrink-0 h-full grow-0">
      <Image
        loading="lazy" 
        src={imageSrc} 
        alt={title}
        className="box-border object-cover overflow-hidden shrink-0 w-full aspect-square min-h-[20px] min-w-[20px]" 
      />
      <h2 className="box-border relative shrink-0 mx-auto mt-5 h-auto text-xl text-black">
        {title}
      </h2>
      <p className="box-border relative shrink-0 mx-auto mt-5 h-auto">
        {description}
      </p>
    </article>
  );
};

export default ImageWithText;